ABRMS-4456 METIS database-init: Kopie von Repo metis Commit 8f0d539
| commit 8f0d539
| Author: Christoph Strebin <christoph.strebin@freenet.ag>
| Date:   2022-11-23 18:53:18 +0100
|
|     ABRMS-4456 Fix SaleschannelControllerTest
|
|     IllegalStateException in com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty
|
|     Property Wert wird da aber gar nicht gebraucht. => lazy abfragen

diff --git a/workflows/metis/backend/database-init.yml b/workflows/metis/backend/database-init.yml
--- a/workflows/metis/backend/database-init.yml
+++ b/workflows/metis/backend/database-init.yml
@@ -1,3 +1,6 @@
+#
+# Generated by repo freenet-group/mcbscore-github-actions / workflow Distribute from file workflows/metis/backend/database-init.yml
+#
 name: "Test-Datenbank löschen und initialisieren"
 
 on:
@@ -25,15 +28,26 @@ on:
         default: main
 
 jobs:
-  deploy:
+  run:
     runs-on: [self-hosted, vm]
-    name: "deploy: ${{ toJSON(inputs) }}"
+    name: "run: ${{ toJSON(inputs) }}"
     env:
       ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
       ACTIONS_PATH: mcbscore/github
       REPOSITORY_PATH: repository
 
     steps:
+      - name: Change Owner to Runner User
+        if: ${{ always() }}
+        run: |
+          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
+          docker run --rm -v "$(pwd):/target" -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"
+
+      - name: Ensure clean workspace
+        run: |
+          echo "Cleaning up previous run"
+          rm -rf *
+
       - name: Checkout Repository
         uses: actions/checkout@v3
         with:
@@ -59,6 +73,8 @@ jobs:
       - name: Initialize Workflow
         uses: ./mcbscore/github/actions/init-workflow
         with:
+          lookupBasePath: ${{ env.REPOSITORY_PATH }}
+          installJq: true
           installJava: true
 
       # Inputs zu handlichen Variablen umwandeln
@@ -69,7 +85,7 @@ jobs:
         run: |
           prof=${GH_INPUT_ENV%%(*}    # ab erster Klammer abschneiden
           prof=${prof//[[:space:]]/}  # trimmen
-          printf '%s=%s\n' SPRING_PROFILE prof | tee -a -- "$GITHUB_ENV"
+          printf '%s=%s\n' SPRING_PROFILE "$prof" | tee -a -- "$GITHUB_ENV"
 
       - name: Download release
         uses: ./mcbscore/github/actions/download-release-assets
@@ -79,17 +95,30 @@ jobs:
           targetPath: ./release
           token: ${{ env.TOKEN }}
 
-      - name: Reset database
+      - name: Start metis-shell
         shell: bash
         env:
           GH_INPUT_COMPONENT_VERSION: ${{ inputs.componentVersion }}
+          GH_INPUT_LOAD_TEST_DATA: ${{ inputs.loadTestData }}
         run: |
-          java -Xmx1g -Dfile.encoding=UTF-8 "-Dspring.profiles.active=$SPRING_PROFILE" \
-            -jar "metis-shell-${GH_INPUT_COMPONENT_VERSION}.jar" resetTestData
+          commands=( resetTestData stacktrace )
+          if "${GH_INPUT_LOAD_TEST_DATA:-true}"; then
+            commands=(
+              "${commands[@]}"
+              "loadTestData --inputFileName '${REPOSITORY_PATH}/metis-rest/src/main/resources/testDataSetFULL.xml'"
+              stacktrace
+            )
+          fi
 
-      - name: Load test data
-        if: inputs.loadTestData == 'true'
-        shell: bash
-        run: |
-          java -Xmx2g -Dfile.encoding=UTF-8 "-Dspring.profiles.active=$SPRING_PROFILE" \
-            -jar "metis-shell-${GH_INPUT_COMPONENT_VERSION}.jar" 'loadTestData --inputFileName testDataSetFULL.xml'
+          printf 'Spring-shell commands:\n'; printf '\t%s\n' "${commands[@]}"
+          printf '%s\n' "${commands[@]}" \
+          | (set -x; java -Xmx2g -Dfile.encoding=UTF-8 "-Dspring.profiles.active=$SPRING_PROFILE" \
+            -jar "release/metis-shell-${GH_INPUT_COMPONENT_VERSION}.jar") \
+          | tee metis-shell.out
+
+          # Status prüfen (Exceptions führen leider nicht zu Spring Shell Exit Status != 0):
+          checkMessage() {
+            if ! grep -q "$@" -- metis-shell.out; then echo "Erwartete Meldung (grep $@) nicht gefunden" >&2; return 1; fi
+          }
+          checkMessage -P '\bresetTestData succeeded\b'
+          if "$GH_INPUT_LOAD_TEST_DATA"; then checkMessage -P '\bloadTestData succeeded\b'; fi
