ABRMS-5319 run-name angepasst, checkout fehlte und falscher aws pfad, k8s deployment aufgenommen

diff --git a/workflows/ms-cicd/deployment.yml b/workflows/ms-cicd/deployment.yml
--- a/workflows/ms-cicd/deployment.yml
+++ b/workflows/ms-cicd/deployment.yml
@@ -1,9 +1,6 @@
-#
-# Generated by repo  / workflow Distribute from file workflows/ms/deployment.yml
-#
 name: Deployment
 #Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
-run-name: Deployment ${{ github.event.inputs.componentVersion }} auf ${{ github.event.inputs.environment }}
+run-name: Deployment ${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }} auf ${{ github.event.inputs.environment }}
 
 on:
   workflow_dispatch:
@@ -63,33 +60,39 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # Secrets aus AWS auslesen
-    - name: Read and set AWS credentials
-      uses: ./actions/read-aws-secrets
-      with:
-        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        awsParameterPairs: |
-          /github/secrets/mcbs_token = TOKEN
+      - name: Checkout Repository
+        # Repository auschecken
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-    - name: Determine deployment ref
-      # DEPLOYMENT_REF Umgebungsvariable setzen
-      shell: bash
-      run: |
-        if  [[ ${{ github.event.inputs.componentVersion }} =~ '-SNAPSHOT' ]] ;
-        then
-          echo "DEPLOYMENT_REF=develop" >> $GITHUB_ENV
-        else
-          echo "DEPLOYMENT_REF=${{ github.event.inputs.componentVersion }}" >> $GITHUB_ENV
-        fi
+      - name: Read and set AWS credentials
+        # Secrets aus AWS auslesen
+        uses: ./.github/actions/read-aws-secrets
+        with:
+          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          awsParameterPairs: |
+            /github/secrets/mcbs_token = TOKEN
 
-    - name: Create GitHub deployment
-      uses: chrnorm/deployment-action@v2
-      id: create-deployment
-      with:
-        token: ${{ env.TOKEN }}
-        environment: ${{ github.event.inputs.environment }}
-        ref: ${{ env.DEPLOYMENT_REF }}
+      - name: Determine deployment ref
+        # DEPLOYMENT_REF Umgebungsvariable setzen
+        shell: bash
+        run: |
+          if  [[ ${{ github.event.inputs.componentVersion }} =~ '-SNAPSHOT' ]] ;
+          then
+            echo "DEPLOYMENT_REF=develop" >> $GITHUB_ENV
+          else
+            echo "DEPLOYMENT_REF=${{ github.event.inputs.componentVersion }}" >> $GITHUB_ENV
+          fi
+
+      - name: Create GitHub deployment
+        uses: chrnorm/deployment-action@v2
+        id: create-deployment
+        with:
+          token: ${{ env.TOKEN }}
+          environment: ${{ github.event.inputs.environment }}
+          ref: ${{ env.DEPLOYMENT_REF }}
 
     outputs:
       deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}
@@ -105,152 +108,174 @@ jobs:
       NODEJS_VERSION: 16
 
     steps:
-    # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
-    - name: Change Owner to Runner User
-      if: ${{ always() }}
-      run: |
-        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
-        docker run --rm -v `pwd`:/target -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"
+      # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
+      - name: Change Owner to Runner User
+        if: ${{ always() }}
+        run: |
+          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
+          docker run --rm -v `pwd`:/target -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"
 
-    - name: Ensure clean workspace
-      # Leeren Workspace sicherstellen
-      run: |
-        echo "Cleaning up previous run"
-        rm -rf *
+      - name: Ensure clean workspace
+        # Leeren Workspace sicherstellen
+        run: |
+          echo "Cleaning up previous run"
+          rm -rf *
 
-    - name: Checkout Repository
-      # Repository auschecken unter $GITHUB_WORKSPACE
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+      - name: Checkout Repository
+        # Repository auschecken unter $GITHUB_WORKSPACE
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-    - name: Read AWS Secrets
-      uses: ./.github/actions/read-aws-secrets
-      with:
-        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        awsParameterPairs: |
+      - name: Read AWS Secrets
+        uses: ./.github/actions/read-aws-secrets
+        with:
+          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          awsParameterPairs: |
             /github/secrets/mcbs_token = TOKEN,
             /github/secrets/deployment_user = DEPLOYMENT_USER,
             /github/secrets/ssh/mdmcbsapi-app/zxrestapi_ppk = SSH_KEY,
             /github/secrets/checkmk_user = CHECKMK_USER, 
             /github/secrets/checkmk_password = CHECKMK_PW
-    - name: checkout mcbscore-github-actions
-      # Die internen Actions auschecken
-      uses: actions/checkout@v3
-      with:
-        repository: ${{ env.ACTIONS_REPOSITORY }}
-        token: ${{ env.TOKEN }}
-        path: ${{ env.ACTIONS_PATH }}
-        ref: ${{ inputs.actionsRepositoryBranch }}
 
-    # Auschecken des Deployment Repositories
-    - name: Checkout Deployment Data / Scripts
-      uses: actions/checkout@v3
-      with:
-        repository: freenet-group/ms-deployment
-        token: ${{ env.TOKEN }}
-        path: ${{ env.DEPLOYMENT_PATH }}
-        ref: ${{ github.event.inputs.deploymentRepositoryBranch }}
+      - name: checkout mcbscore-github-actions
+        # Die internen Actions auschecken
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ env.ACTIONS_REPOSITORY }}
+          token: ${{ env.TOKEN }}
+          path: ${{ env.ACTIONS_PATH }}
+          ref: ${{ inputs.actionsRepositoryBranch }}
 
-    # ##################################################################################
-    # Initialize Workflow
-    # ##################################################################################
+      # Auschecken des Deployment Repositories
+      - name: Checkout Deployment Data / Scripts
+        uses: actions/checkout@v3
+        with:
+          repository: freenet-group/ms-deployment
+          token: ${{ env.TOKEN }}
+          path: ${{ env.DEPLOYMENT_PATH }}
+          ref: ${{ github.event.inputs.deploymentRepositoryBranch }}
 
-    - name: Initialize Workflow
-      uses: ./mcbscore/github/actions/init-workflow
-      with:
-        installJavaWithNashornEngine: true
-        installNodeJs: true
-        installJq: true
+      # ##################################################################################
+      # Initialize Workflow
+      # ##################################################################################
 
-    - name: Download Release
-      id: downloadRelease
-      uses: ./mcbscore/github/actions/download-release-assets
-      with:
-        version: ${{ github.event.inputs.componentVersion }}
-        assetPattern: '${{ github.event.inputs.component }}.jar'
-        targetPath: './${{ env.DEPLOYMENT_PATH }}/release'
-        token: ${{ env.TOKEN }}
+      - name: Initialize Workflow
+        uses: ./mcbscore/github/actions/init-workflow
+        with:
+          installJavaWithNashornEngine: true
+          installNodeJs: true
+          installJq: true
 
-    # Standard Deployment
-    - name: Deployment
-      id: deployRelease
-      if: ${{ github.event.inputs.additionalDeploymentComponent == '' }}
-      uses: ./mcbscore/github/actions/deploy-microservice
-      with:
-        component: ${{ github.event.inputs.component }}
-        stage: ${{ github.event.inputs.environment }}
-        componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
-        dockerImage: ghcr.io/freenet-group/mcbs-core/ms-${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }}
-        checkMkUser: ${{ env.CHECKMK_USER }}
-        checkMkSecret: ${{ env.CHECKMK_PW }}
-        deploymentUser: ${{ env.DEPLOYMENT_USER }}
-        sshKey: ${{ env.SSH_KEY }}
-        dockerRegistryToken: ${{ env.TOKEN }}
+      - name: Download Release
+        id: downloadRelease
+        uses: ./mcbscore/github/actions/download-release-assets
+        with:
+          version: ${{ github.event.inputs.componentVersion }}
+          assetPattern: '${{ github.event.inputs.component }}.jar'
+          targetPath: './${{ env.DEPLOYMENT_PATH }}/release'
+          token: ${{ env.TOKEN }}
 
-    # Custom Deployment
-    - name: Deployment
-      id: additionalDeployment
-      if: ${{ github.event.inputs.additionalDeploymentComponent != '' }}
-      uses: ./mcbscore/github/actions/deploy-microservice
-      with:
-        component: ${{ github.event.inputs.additionalDeploymentComponent }}
-        stage: ${{ github.event.inputs.environment }}
-        componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
-        checkMkUser: ${{ env.CHECKMK_USER }}
-        checkMkSecret: ${{ env.CHECKMK_PW }}
-        deploymentUser: ${{ env.DEPLOYMENT_USER }}
-        sshKey: ${{ env.SSH_KEY }}
+      # Standard Deployment
+      - name: Deployment
+        id: deployRelease
+        if: ${{ github.event.inputs.additionalDeploymentComponent == '' }}
+        uses: ./mcbscore/github/actions/deploy-microservice
+        with:
+          component: ${{ github.event.inputs.component }}
+          stage: ${{ github.event.inputs.environment }}
+          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
+          dockerImage: ghcr.io/freenet-group/mcbs-core/ms-${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }}
+          checkMkUser: ${{ env.CHECKMK_USER }}
+          checkMkSecret: ${{ env.CHECKMK_PW }}
+          deploymentUser: ${{ env.DEPLOYMENT_USER }}
+          sshKey: ${{ env.SSH_KEY }}
+          dockerRegistryToken: ${{ env.TOKEN }}
 
-    # Deployment als erfolgreich markieren
-    - name: Update deployment status (success)
-      if: success()
-      uses: chrnorm/deployment-status@v2
-      with:
-        token: ${{ env.TOKEN }}
-        state: "success"
-        deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}
+      # Custom Deployment
+      - name: Deployment
+        id: additionalDeployment
+        if: ${{ github.event.inputs.additionalDeploymentComponent != '' }}
+        uses: ./mcbscore/github/actions/deploy-microservice
+        with:
+          component: ${{ github.event.inputs.additionalDeploymentComponent }}
+          stage: ${{ github.event.inputs.environment }}
+          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
+          checkMkUser: ${{ env.CHECKMK_USER }}
+          checkMkSecret: ${{ env.CHECKMK_PW }}
+          deploymentUser: ${{ env.DEPLOYMENT_USER }}
+          sshKey: ${{ env.SSH_KEY }}
 
-    # Deployment als fehlerhaft markieren
-    - name: Update deployment status (failure)
-      if: failure()
-      uses: chrnorm/deployment-status@v2
-      with:
-        token: ${{ env.TOKEN }}
-        state: "failure"
-        deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}
+      # Deployment als erfolgreich markieren
+      - name: Update deployment status (success)
+        if: success()
+        uses: chrnorm/deployment-status@v2
+        with:
+          token: ${{ env.TOKEN }}
+          state: "success"
+          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}
+
+      # Deployment als fehlerhaft markieren
+      - name: Update deployment status (failure)
+        if: failure()
+        uses: chrnorm/deployment-status@v2
+        with:
+          token: ${{ env.TOKEN }}
+          state: "failure"
+          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}
 
     outputs:
       componentName: ${{ env.JIRA_COMPONENT }}
 
+  deploy_k8s:
+    runs-on: ubuntu-latest
+    needs: create-deployment
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - id: FileExists
+        run: |
+          echo "k8sExists=${{hashFiles('**/deployment_k8s.yml')}}" >> "$GITHUB_OUTPUT"
+
+      - name: deploy_k8s
+        if: ${{ steps.FileExists.outputs.k8sExists != '' }
+        uses: freenet-group/mcbscore-reusable-workflows/.github/workflows/deployment_k8s.yml@main
+        with:
+          componentVersion: ${{ github.event.inputs.componentVersion }}
+          environment: ${{ github.event.inputs.environment }}
+          component: ${{ github.event.inputs.component }}
+
   bambi-notification:
     # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
     runs-on: [self-hosted, k8s]
-    needs: deploy
-    if: ${{ always() && !contains(needs.deploy.result, 'failure') && !contains(needs.deploy.result, 'cancelled') && (github.event.inputs.environment == 'git' || github.event.inputs.environment == 'b2b' || github.event.inputs.environment == 'prod') }}
+    needs: [deploy, deploy_k8s]
+    #Der Check success() ist nicht true bei geskippten workflows. !failure() dahingegen sieht geskippte nicht als failure und nur rote Steps
+    if: ${{ always() && !failure() && !contains(needs.deploy.result, 'failure') && !contains(needs.deploy.result, 'cancelled') && (github.event.inputs.environment == 'git' || github.event.inputs.environment == 'b2b' || github.event.inputs.environment == 'prod') }}
     steps:
-    # Deployment als erfolgreich melden
-    - name: Report deployment status
-      shell: bash
-      run: |
-        curlResult=$(curl -sw %{http_code} --location --request POST 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v2/bambi/deployment/environmentversion' \
-        --header 'Content-Type: application/json' \
-        --data-raw '{
-          "version": "${{ github.event.inputs.componentVersion }}",
-          "componentName": "${{ needs.deploy.outputs.componentName }}",
-          "workflowName": "${{ github.workflow }}",
-          "environment": "${{ github.event.inputs.environment }}",
-          "extern": false,
-          "workflowRunId": ${{ github.run_id }},
-          "deployState": "successfull",
-          "deployUser": "${{ github.actor }}"
-        }')
-        echo "Result: $curlResult"
-        statusCode="${curlResult:${#curlResult}-3}"
-        echo "statusCode: $statusCode"
-
-        if [[ "statusCode" -ge "400" ]]; then
+      # Deployment als erfolgreich melden
+      - name: Report deployment status
+        shell: bash
+        run: |
+          curlResult=$(curl -sw %{http_code} --location --request POST 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v2/bambi/deployment/environmentversion' \
+          --header 'Content-Type: application/json' \
+          --data-raw '{
+            "version": "${{ github.event.inputs.componentVersion }}",
+            "componentName": "${{ needs.deploy.outputs.componentName }}",
+            "originComponentName": "${{ github.event.inputs.component }}",
+            "workflowName": "${{ github.workflow }}",
+            "environment": "${{ github.event.inputs.environment }}",
+            "extern": false,
+            "workflowRunId": ${{ github.run_id }},
+            "deployState": "successfull",
+            "deployUser": "${{ github.actor }}"
+          }')
           echo "Result: $curlResult"
-          exit 1
-        fi
+          statusCode="${curlResult:${#curlResult}-3}"
+          echo "statusCode: $statusCode"
+          
+          if [[ "statusCode" -ge "400" ]]; then
+            echo "Result: $curlResult"
+            exit 1
+          fi
